### ISSUE TITLE
You need to add the ability to pass command arguments

### ISSUE THREAD

**Issue by LKirillK** [72-S/CommandBridge#5]
Here is an example
/ban player
{args} = player

name: ban
enabled: true
commands:
  - command: 'ban {args}' #need to add the ability to pass command arguments
    target-executor: 'console'
    target-server-ids: ['proxy']

Or you can do this
/punish player lvl2
{args[0]} = player
{args[1]} = lvl2
name: punish
enabled: true
commands:
  - command: 'lp user {args[0]} parent add {args[1]}' #need to add the ability to pass command arguments
    target-executor: 'console'
    target-server-ids: ['proxy']

**Comment by 72-S** [comment]
Currently, the plugin does support passing arguments using the `%args%` placeholder, which captures the entire string of arguments from a command. However, the ability to extract specific arguments (e.g., using `[0]` for the first argument) is not yet implemented. As of now, `%args%` will always be replaced by the whole string.

For example, a configuration for the `/kill` command would look like this:

```yaml
name: test-kill
enabled: true
commands:
  command: "kill %args%"
  target-executor: 'console'
  target-server-ids: ['survival']
```
The command would look like this: `/test-kill RealPlayerName`

This example applies to Bukkit server commands, but the process is the same for commands executed on a Velocity server.

I can certainly implement the feature to allow using `[index]` for specific arguments, like `{args[0]}` for the first argument, as you mentioned in your example:

```yaml
/punish player lvl2
{args[0]} = player
{args[1]} = lvl2
name: punish
enabled: true
commands:
  command: "lp user {args[0]} parent add {args[1]}"
  target-executor: 'console'
  target-server-ids: ['proxy']
```

I'll work on adding this functionality. Apologies for the confusion; I'll also make sure to update the wiki once it's available.

Would you like me to prioritize this update?
